### ISSUE TITLE
cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by elhammoumi** [llSourcell/how_to_deploy_a_keras_model_to_production#3]
I get this error: 
`Traceback (most recent call last):
  File "C:\Users\Oussama\AppData\Local\Programs\Python\Python35\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Oussama\AppData\Local\Programs\Python\Python35\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Oussama\AppData\Local\Programs\Python\Python35\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Oussama\AppData\Local\Programs\Python\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\Oussama\AppData\Local\Programs\Python\Python35\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Oussama\AppData\Local\Programs\Python\Python35\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 56, in predict
    convertImage(imgData)
  File "app.py", line 36, in convertImage
    imgstr = re.search(r'base64,(.*)',imgData1).group(1)
  File "C:\Users\Oussama\AppData\Local\Programs\Python\Python35\lib\re.py", line 173, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object`

**Comment by elhammoumi** [comment]
I fixed the issue using this code
`def convertImage(imgData1):
	imgstr = re.search(b'base64,(.*)',imgData1).group(1)
	#print(imgstr)
	with open('output.png','wb') as output:
		output.write(base64.b64decode(imgstr))`

**Comment by legqio** [comment]
@elhammoumi thank you! don't forget the    import base64

**Comment by chandu-v** [comment]
Thank you.
It helped me to fix.
If it's fixed, we can close it.
